version: "3.1"
services:

    mysqldb:
      image: mysql:5.7
      container_name: voucherpool-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=news2go
        - MYSQL_USER=news2user
        - MYSQL_PASSWORD=news2pass
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: voucherpool-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: voucherpool-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

